# Default configuration for experiments
model:
  name: "lmsys/vicuna-7b-v1.5"
  num_heads: 32
  head_dim: 128
  max_length: 512

dataset:
  name: "xsum"
  split: "test[:500]"

evaluation:
  num_samples: 100
  save_attention_patterns: true
  metrics:
    - "perplexity"
    - "memory_usage"
    - "inference_time"
    - "attention_sparsity"

hardware:
  device: "cuda"
  precision: "float16"

liquidfusion:
  attention_sink_size: 4
  heavy_hitter_ratio: 0.2
  max_position_embeddings: 2048

h2o:
  cache_ratio: 0.2
  max_cache_size: 1024

streaming:
  sink_size: 4
  window_size: 256

visualization:
  format: "png"
  dpi: 300
  style: "whitegrid"